Attribute VB_Name = "modLoader"
Option Explicit

' Stable development loader. This module never removes or reloads itself.
Private Const BUILD_SOURCE_FOLDER As String = "{{BUILD_SOURCE_FOLDER}}"
Private Const BUILD_ADDIN_FILE As String = "{{BUILD_ADDIN_FILE}}"
Private Const MANAGED_TAG As String = "@ManagedByDouglasTools"
Private Const SETTINGS_APP As String = "DFSTools"
Private Const SETTINGS_SECTION As String = "Paths"
Private Const SETTINGS_KEY As String = "SourceFolder"

Public Sub RibbonReloadMacros(ByVal control As Office.IRibbonControl)
    ReloadExternalModules
End Sub

Public Sub ReloadExternalModules()
    Dim sourceFolder As String
    Dim project As Object
    Dim sourceFiles As Collection
    Dim sourceNames As Collection
    Dim tempRoot As String
    Dim backupFolder As String
    Dim importFolder As String
    Dim removedCount As Long
    Dim importedCount As Long
    Dim mutationStarted As Boolean
    Dim errorNumber As Long
    Dim errorDescription As String

    On Error GoTo Failed

    sourceFolder = ResolveSourceFolder()
    If Len(sourceFolder) = 0 Then Exit Sub

    Set project = GetHostProject()
    Set sourceFiles = CollectSourceModules(sourceFolder, sourceNames)
    ValidateModuleCollisions project, sourceNames

    tempRoot = CreateReloadFolder()
    backupFolder = tempRoot & "backup\"
    importFolder = tempRoot & "incoming\"
    CreateFolder backupFolder
    CreateFolder importFolder

    BackupManagedModules project, backupFolder
    modMacroLauncher.CloseMacroLauncher

    mutationStarted = True
    removedCount = RemoveManagedModules(project)
    importedCount = ImportSourceModules(project, sourceFiles, importFolder)

    DeleteFolderIfPossible tempRoot
    ShowReloadResult "Macros recarregadas: " & importedCount & _
                     " modulos importados e " & removedCount & " substituidos.", "complete"
    Exit Sub

Failed:
    errorNumber = Err.Number
    errorDescription = Err.Description

    If mutationStarted Then
        On Error Resume Next
        RemoveManagedModules project
        ImportBackupModules project, backupFolder
        If Err.Number <> 0 Then
            errorDescription = errorDescription & vbCrLf & vbCrLf & _
                "A restauracao automatica tambem falhou. Backup: " & backupFolder
        Else
            errorDescription = errorDescription & vbCrLf & vbCrLf & _
                "Os modulos anteriores foram restaurados."
        End If
        On Error GoTo 0
    End If

    ShowReloadResult "Falha ao recarregar macros. Erro " & errorNumber & _
                     ": " & errorDescription, "error"
End Sub

Private Sub ShowReloadResult(ByVal message As String, ByVal state As String)
    On Error Resume Next
    modMacroLauncher.ShowMacroLauncher
    modMacroLauncher.ShowLauncherResult message, state
    On Error GoTo 0
End Sub

Private Function GetHostProject() As Object
    Dim projects As Object
    Dim candidate As Object
    Dim component As Object
    Dim projectFile As String
    Dim fileSystem As Object

    On Error GoTo AccessFailed
    Set projects = Application.VBE.VBProjects
    Set fileSystem = CreateObject("Scripting.FileSystemObject")

    ' Prefer the project whose backing file matches the PPAM generated by the
    ' build. Hidden PowerPoint add-ins are not consistently addressable through
    ' the Presentations collection.
    For Each candidate In projects
        projectFile = vbNullString
        On Error Resume Next
        projectFile = candidate.FileName
        On Error GoTo AccessFailed
        If Len(projectFile) > 0 Then
            If StrComp(fileSystem.GetFileName(projectFile), BUILD_ADDIN_FILE, vbTextCompare) = 0 Then
                Set GetHostProject = candidate
                Exit Function
            End If
        End If
    Next candidate

    ' Fallback for hosts that do not expose VBProject.FileName for loaded PPAMs.
    ' Only this add-in contains the stable modLoader module.
    For Each candidate In projects
        Set component = Nothing
        On Error Resume Next
        Set component = candidate.VBComponents("modLoader")
        On Error GoTo AccessFailed
        If Not component Is Nothing Then
            Set GetHostProject = candidate
            Exit Function
        End If
    Next candidate

    Err.Raise vbObjectError + 2099, "DFS Tools", _
        "O projeto VBA do add-in " & BUILD_ADDIN_FILE & " nao foi encontrado."
    Exit Function

AccessFailed:
    Err.Raise vbObjectError + 2098, "DFS Tools", _
        "Nao foi possivel acessar os projetos VBA: " & Err.Description
End Function

Private Function ResolveSourceFolder() As String
    Dim configured As String
    Dim candidate As String

    configured = GetSetting(SETTINGS_APP, SETTINGS_SECTION, SETTINGS_KEY, vbNullString)
    If FolderExists(configured) Then
        ResolveSourceFolder = EnsureTrailingSlash(configured)
        Exit Function
    End If

    candidate = BUILD_SOURCE_FOLDER
    If FolderExists(candidate) Then
        SaveSetting SETTINGS_APP, SETTINGS_SECTION, SETTINGS_KEY, candidate
        ResolveSourceFolder = EnsureTrailingSlash(candidate)
        Exit Function
    End If

    candidate = ChooseSourceFolder()
    If Len(candidate) > 0 Then
        SaveSetting SETTINGS_APP, SETTINGS_SECTION, SETTINGS_KEY, candidate
        ResolveSourceFolder = EnsureTrailingSlash(candidate)
    End If
End Function

Private Function ChooseSourceFolder() As String
    Dim picker As FileDialog
    Set picker = Application.FileDialog(msoFileDialogFolderPicker)
    With picker
        .Title = "Selecione a pasta src com os arquivos .bas"
        .AllowMultiSelect = False
        If .Show = -1 Then ChooseSourceFolder = .SelectedItems(1)
    End With
End Function

Private Function CollectSourceModules(ByVal sourceFolder As String, ByRef names As Collection) As Collection
    Dim files As New Collection
    Dim foundNames As New Collection
    Dim fileName As String
    Dim filePath As String
    Dim codeText As String
    Dim componentName As String
    Dim duplicateError As Long

    fileName = Dir$(EnsureTrailingSlash(sourceFolder) & "*.bas")
    Do While Len(fileName) > 0
        If LCase$(fileName) <> "modloader.bas" Then
            filePath = EnsureTrailingSlash(sourceFolder) & fileName
            codeText = ReadUtf8File(filePath)
            componentName = ReadComponentName(codeText)
            If Len(componentName) = 0 Then
                Err.Raise vbObjectError + 2100, "DFS Tools", "VB_Name ausente em " & fileName
            End If
            If InStr(1, codeText, MANAGED_TAG, vbTextCompare) = 0 Then
                Err.Raise vbObjectError + 2101, "DFS Tools", "Modulo sem marcador gerenciado: " & fileName
            End If

            On Error Resume Next
            Err.Clear
            foundNames.Add componentName, LCase$(componentName)
            duplicateError = Err.Number
            Err.Clear
            On Error GoTo 0
            If duplicateError <> 0 Then
                Err.Raise vbObjectError + 2102, "DFS Tools", "Modulo duplicado nas fontes: " & componentName
            End If
            files.Add filePath
        End If
        fileName = Dir$
    Loop

    If files.Count = 0 Then
        Err.Raise vbObjectError + 2103, "DFS Tools", "Nenhum modulo .bas gerenciado encontrado em " & sourceFolder
    End If

    Set names = foundNames
    Set CollectSourceModules = files
End Function

Private Sub ValidateModuleCollisions(ByVal project As Object, ByVal sourceNames As Collection)
    Dim component As Object
    For Each component In project.VBComponents
        If CollectionContains(sourceNames, component.Name) Then
            If Not IsManagedComponent(component) Then
                Err.Raise vbObjectError + 2104, "DFS Tools", _
                    "A fonte colide com um modulo nao gerenciado: " & component.Name
            End If
        End If
    Next component
End Sub

Private Sub BackupManagedModules(ByVal project As Object, ByVal backupFolder As String)
    Dim component As Object
    For Each component In project.VBComponents
        If IsManagedComponent(component) Then
            If component.Type <> 1 Then
                Err.Raise vbObjectError + 2105, "DFS Tools", _
                    "Tipo de modulo gerenciado nao suportado no reload: " & component.Name
            End If
            component.Export backupFolder & component.Name & ".bas"
        End If
    Next component
End Sub

Private Function RemoveManagedModules(ByVal project As Object) As Long
    Dim index As Long
    Dim component As Object

    For index = project.VBComponents.Count To 1 Step -1
        Set component = project.VBComponents(index)
        If IsManagedComponent(component) Then
            project.VBComponents.Remove component
            RemoveManagedModules = RemoveManagedModules + 1
        End If
    Next index
End Function

Private Function ImportSourceModules(ByVal project As Object, ByVal files As Collection, ByVal importFolder As String) As Long
    Dim sourcePath As Variant
    Dim importPath As String
    Dim fileName As String

    For Each sourcePath In files
        fileName = Mid$(CStr(sourcePath), InStrRev(CStr(sourcePath), "\") + 1)
        importPath = importFolder & fileName
        ConvertUtf8ToAnsi CStr(sourcePath), importPath
        project.VBComponents.Import importPath
        ImportSourceModules = ImportSourceModules + 1
    Next sourcePath
End Function

Private Sub ImportBackupModules(ByVal project As Object, ByVal backupFolder As String)
    Dim fileName As String
    fileName = Dir$(backupFolder & "*.bas")
    Do While Len(fileName) > 0
        project.VBComponents.Import backupFolder & fileName
        fileName = Dir$
    Loop
End Sub

Private Function IsManagedComponent(ByVal component As Object) As Boolean
    Dim lineCount As Long
    Dim headerText As String

    If component.Name = "modLoader" Or component.Name = "modCommandCatalog" Then Exit Function
    If component.Type <> 1 Then Exit Function

    lineCount = component.CodeModule.CountOfLines
    If lineCount > 25 Then lineCount = 25
    If lineCount > 0 Then headerText = component.CodeModule.Lines(1, lineCount)
    IsManagedComponent = (InStr(1, headerText, MANAGED_TAG, vbTextCompare) > 0)
End Function

Private Function ReadComponentName(ByVal codeText As String) As String
    Dim lines As Variant
    Dim line As Variant
    Dim quoteStart As Long
    Dim quoteEnd As Long

    lines = Split(Replace(codeText, vbCrLf, vbLf), vbLf)
    For Each line In lines
        If InStr(1, CStr(line), "Attribute VB_Name", vbTextCompare) > 0 Then
            quoteStart = InStr(1, CStr(line), Chr$(34))
            quoteEnd = InStr(quoteStart + 1, CStr(line), Chr$(34))
            If quoteStart > 0 And quoteEnd > quoteStart Then
                ReadComponentName = Mid$(CStr(line), quoteStart + 1, quoteEnd - quoteStart - 1)
                Exit Function
            End If
        End If
    Next line
End Function

Private Function ReadUtf8File(ByVal filePath As String) As String
    Dim stream As Object
    Set stream = CreateObject("ADODB.Stream")
    stream.Type = 2
    stream.Charset = "utf-8"
    stream.Open
    stream.LoadFromFile filePath
    ReadUtf8File = stream.ReadText
    stream.Close
End Function

Private Sub ConvertUtf8ToAnsi(ByVal sourcePath As String, ByVal destinationPath As String)
    Dim inputStream As Object
    Dim outputStream As Object
    Dim codeText As String

    codeText = ReadUtf8File(sourcePath)
    Set outputStream = CreateObject("ADODB.Stream")
    outputStream.Type = 2
    outputStream.Charset = "windows-1252"
    outputStream.Open
    outputStream.WriteText codeText
    outputStream.SaveToFile destinationPath, 2
    outputStream.Close
End Sub

Private Function CollectionContains(ByVal values As Collection, ByVal key As String) As Boolean
    Dim value As Variant
    On Error Resume Next
    value = values(LCase$(key))
    CollectionContains = (Err.Number = 0)
    Err.Clear
    On Error GoTo 0
End Function

Private Function EnsureTrailingSlash(ByVal folderPath As String) As String
    folderPath = Trim$(folderPath)
    If Len(folderPath) > 0 And Right$(folderPath, 1) <> "\" Then folderPath = folderPath & "\"
    EnsureTrailingSlash = folderPath
End Function

Private Function FolderExists(ByVal folderPath As String) As Boolean
    If Len(Trim$(folderPath)) = 0 Then Exit Function
    FolderExists = CreateObject("Scripting.FileSystemObject").FolderExists(folderPath)
End Function

Private Function CreateReloadFolder() As String
    Dim folderPath As String
    folderPath = Environ$("TEMP") & "\DFSToolsReload_" & _
                 Format$(Now, "yyyymmdd_hhnnss") & "_" & CStr(Int(Timer * 100))
    CreateFolder folderPath
    CreateReloadFolder = EnsureTrailingSlash(folderPath)
End Function

Private Sub CreateFolder(ByVal folderPath As String)
    CreateObject("Scripting.FileSystemObject").CreateFolder folderPath
End Sub

Private Sub DeleteFolderIfPossible(ByVal folderPath As String)
    On Error Resume Next
    CreateObject("Scripting.FileSystemObject").DeleteFolder folderPath, True
    On Error GoTo 0
End Sub
